import numpy as np
import matplotlib.pyplot as plt
x = np.linspace(-2*np.pi, 2*np.pi, 50)
y = np.sin(x)
z = np.cos(x)
plt.subplot(2, 2, 1)
plt.plot(x, y, 'ro--')
plt.title('Sine Wave')
plt.xlabel('x-axis')
plt.ylabel('y-axis')
plt.legend(('$y=sinx$', ""), loc=1)
plt.subplot(2, 2, 4)
plt.plot(x, z, 'bD:')
plt.title('Cosine Wave')
plt.xlabel('x-axis')
plt.ylabel('y-axis')
plt.legend(('$y=cosx$', ''), loc=1)
plt.savefig('images/subplot.jpg')
plt.show()
